spring:
  cloud:
    # nacos
    nacos:
      discovery:
        group: '@nacos.group@'
        server-addr: '@nacos.server.addr@'
    # sentinel
    sentinel:
      transport:
        dashboard: '@sentinel.dashboard.addr@'
      log:
        dir: logs/redis/sentinel
  # redis单机配置
  redis-standalone:
    host-name: localhost
    port: 6379
    database: 0
    password: '123456'
    lettuce:
      pool:
        # 最大空闲
        max-idle: 8
        # 最小空闲
        min-idle: 0
  # redis哨兵集群配置
  redis-sentinel:
    enable: false
    sentinel:
      master: mymaster
      nodes: localhost:36380,localhost:36381,localhost:36379
    password: '123456'
    lettuce:
      pool:
        # 最大空闲
        max-idle: 8
        # 最小空闲
        min-idle: 0

security:
  oauth2:
    resource:
      jwt:
        # jwt公钥获取地址
        # Note: 需要先启动授权服务器
        key-uri: "http://localhost:9007/oauth/token_key"

# 自定义属性
custom:
  # 项目基础包
  projectPackage: com.github.pandaz
