spring:
  cloud:
    # nacos
    nacos:
      discovery:
        server-addr: localhost:8848
    # sentinel
    sentinel:
      transport:
        dashboard: localhost:8787
      log:
        dir: logs/file-server/sentinel
# mongodb配置
mongodb:
  primary:
    host: 172.16.2.130:27017
    name: admin
    user: admin
    pwd: 123456
  secondary:
    host: 172.16.2.130:27017
    name: admin
    user: admin
    pwd: 123456

# 自定义属性
custom:
  # 项目基础包
  projectPackage: com.github.pandaz
