spring:
  cloud:
    #nacos
    nacos:
      discovery:
        server-addr: 172.16.2.130:8848
    #sentinel
    sentinel:
      transport:
        dashboard: 172.16.2.130:8787
  #数据库配置
  datasource:
    url: jdbc:mysql://172.16.2.130:3306/pandaz?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: pandaz
    password: K0tXBGwNHBl#
    driver-class-name: com.mysql.cj.jdbc.Driver
    #hikari连接池
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: UserCenterAppHikariPool
      maximum-pool-size: 20
      minimum-idle: 10
      connection-test-query: SELECT 1
      connection-timeout: 60000
  #连接redis-sentinel集群配置
  redis:
    timeout: 6000ms
    password: 123456
    lettuce:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1ms
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
    sentinel:
      master: mymaster
      nodes: 172.16.2.130:26380,172.16.2.130:26381,172.16.2.130:26382

#mybatis配置
mybatis:
  mapper-locations: classpath:mybatis/mappers/**/*.xml
  type-aliases-package: com.pandaz.usercenter.entity
  config-location: classpath:mybatis/mybatis-config.xml

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#自定义属性
custom:
  #项目基础包
  projectPackage: com.pandaz
  #调用服务名称
  client:
    redis-server: pandaz-redis
    file-server: pandaz-file-server
  cache:
    #缓存过期时间，单位：分钟
    masterEntryTtlUnit: minutes
    masterEntryTtl: 1
    secondaryEntryTtlUnit: minutes
    secondaryEntryTtl: 10


