version: "2"
services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    volumes:
      - ./nacos/standalone-logs/:/home/nacos/logs
      - ./nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
  sentinel:
    container_name: sentinel
    image: bladex/sentinel-dashboard:latest
    ports:
      - "8787:8858"
    depends_on:
      - nacos
    restart: on-failure