spring:
  cloud:
    #gateway
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: pandaz-user-center
          uri: lb://pandaz-user-center
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
    #nacos
    nacos:
      discovery:
        server-addr: 172.16.2.130:8848
    #sentinel
    sentinel:
      transport:
        dashboard: 172.16.2.130:8787
      log:
        dir: logs/api-gateway/sentinel
#自定义属性
custom:
  #项目基础包
  projectPackage: com.pandaz



