spring:
  servlet:
    multipart:
      max-file-size: 100MB
  cloud:
    # nacos
    nacos:
      discovery:
        group: '@nacos.group@'
        server-addr: '@nacos.server.addr@'
    # sentinel
    sentinel:
      transport:
        dashboard: '@sentinel.dashboard.addr@'
      log:
        dir: logs/file-server/sentinel

# mongodb配置
mongodb:
  primary:
    # 现行方式，方便集群配置
    # 格式 mongodb://[username:password@]host1[:port1][,host2[:port2],...[,hostN[:portN]]][/[database][?options]]
    uri: mongodb://admin:123456@localhost:27017/admin
    # 单体连接，当前项目已过时
    host: localhost:27017
    name: admin
    user: admin
    pwd: 123456
  secondary:
    # 现行方式，方便集群配置
    # 格式 mongodb://[username:password@]host1[:port1][,host2[:port2],...[,hostN[:portN]]][/[database][?options]]
    uri: mongodb://admin:123456@localhost:27017/admin
    # 单体连接，当前项目已过时
    host: localhost:27017
    name: admin
    user: admin
    pwd: 123456

# ftp及连接池配置
ftp:
  open: false
  host: 127.0.0.1
  port: 9021
  username: pandaz
  password: pandaz
  buffer-size: 8096
  initial-size: 5
  max-idle: 8
  retries: 3
  encoding: UTF-8
  test-on-borrow: true
  test-on-return: true
  test-while-idle: true
  min-evictable-idle-time-millis: 60000
  soft-min-evictable-idle-time-millis: 50000
  time-between-eviction-runs-millis: 30000

# 自定义属性
custom:
  # 项目基础包
  projectPackage: com.github.pandaz