spring:
  servlet:
    multipart:
      max-file-size: 50MB
  cloud:
    # alibaba nacos
    nacos:
      discovery:
        server-addr: localhost:8848
    # alibaba sentinel
    sentinel:
      transport:
        dashboard: localhost:8787
      log:
        dir: logs/auth/sentinel

  # 数据库配置
  datasource:
    ds0:
      jdbc-url: jdbc:mysql://localhost:3306/pandaz?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&allowMultiQueries=true
      username: pandaz
      password: K0tXBGwNHBl#
      driver-class-name: com.mysql.cj.jdbc.Driver
      pool-name: AuthAppHikariPool-ds0
      maximum-pool-size: 20
      minimum-idle: 10
      connection-test-query: SELECT 1
      connection-timeout: 60000
    ds1:
      jdbc-url: jdbc:mysql://localhost:3306/activiti?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&allowMultiQueries=true
      username: pandaz
      password: K0tXBGwNHBl#
      driver-class-name: com.mysql.cj.jdbc.Driver
      pool-name: AuthAppHikariPool-ds1
      maximum-pool-size: 20
      minimum-idle: 10
      connection-test-query: SELECT 1
      connection-timeout: 60000

  redis:
    # 单机配置开始
    host: localhost
    port: 6379
    # 单机配置结束
    timeout: 6000ms
    password: 123456
    lettuce:
      pool:
        # 最大连接数
        max-active: 8
        # 最大阻塞等待时间(负数表示没限制)
        max-wait: -1ms
        # 最大空闲
        max-idle: 8
        # 最小空闲
        min-idle: 0
    # 哨兵集群配置
#    sentinel:
#      master: mymaster
#      nodes: localhost:36380,localhost:36381,localhost:36379

# 开启feign对sentinel的支持
# SentinelFeignAutoConfiguration
feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        # 设置Feign的超时时间
        connectTimeout: 3000
        readTimeout: 15000

# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mybatis/mappers/**/*.xml
  type-aliases-package: com.github.pandaz.auth.entity
  config-location: classpath:mybatis/mybatis-config.xml
  global-config:
    db-config:
      logic-not-delete-value: 0

# Swagger ui增强
knife4j:
  production: false

# jetcache
jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote:
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      # 单机配置
      uri: redis://123456@localhost:6379/0
      # 集群配置
      #      uri: redis-sentinel://123456@localhost:36380,localhost:36381,localhost:36379/?sentinelMasterId=mymaster
      #readFrom: slavePreferred

# 自定义属性
custom:
  # 系统编码
  os-code: portal
  # 排除路径
  excluded-paths:
    - "/oauth/**"
    - "/token/**"
    - "/ws/**"
    - "/common/**"
    - "/login"
    - "/v2/api-docs"
    - "/wakeUp"
  # 随机数
  random: ${random.int[0,10]}
  # 开启验证码校验
  captcha:
    enable: true
  # 超级管理员角色
  super-admin:
    enable: false
    name: ROLE_SUPER_ADMIN
  # 项目基础包
  projectPackage: com.github.pandaz
  # swagger
  swagger:
    # api基础包
    base-package: "com.github.pandaz.auth.controller"
    # oauth2授权服务器地址
    auth-server: "http://localhost:9007"
    # 标题
    title: "PandaZ - Auth APIs"
    # 简介
    description: ""
    # 作者
    name: "Carzer"
    # url
    url: ""
    # 邮箱
    email: "Carzer1020@163.com"
    # 版本
    version: "v0.1"
  oauth2:
    # 非对称RSA密钥对 2048位 PKCS#1
    # openssl genrsa -out jwt.pem 2048
    # openssl rsa -in jwt.pem
    privateKey: |
      -----BEGIN RSA PRIVATE KEY-----
      MIICXAIBAAKBgQCAzDxTx+zRtvJHX3a7MU1xBBBQ0/d1orZ7gPvzMGyo4S06/CRd
      u85rNqwkNLbYeYkQkUYuw0zeLFKFqI04WWg8Gavuy/gGBd4jAZEHjMZo4GCnXGEu
      8Bkib4fSukm8m+63zWCpwL7tHjLpqqFzsMY0tRTCJV/LxZIdvUDAZZk18QIDAQAB
      AoGALS85VM0VFEeBvK9NeINl3ymlTa3nKRJBwZcxDJJm9GI223Qcj/O0iWFfR75k
      jRIqFzFX9UzXuTPEaZaFoIihK763/N0VgjqYzqC64lb6uziJYLy3U2Zgexvk2Lx/
      5X9ugpfm1Qvu3/oaw61obacpbbgnckCf8o+KImt8FGRDpE8CQQCV8EfgtOAoCSw0
      CD5W8ceboVhGYl18qXnUpMsj4ZyY1tIvGx3r74N6NTNrD326h29Kj3aPH71QE1Fo
      TiPoZyHfAkEA2+epETGNRZxudE62hFKjLkKN7DZYSb6CEdq7oolOWEighKm8R8Og
      s3+xiVdH8dAPyGfF5i7USs8P4NS/8uHCLwJAS6XMDfIT+f8Ovz29fg5EQB/6MqCk
      PCYhYoi2OOc2I+KWbs/Gm+fetMSsqYJKU9bK7ppNHc7Mq97jPrXV5gZKjwJBAJ23
      IWeGbXbegc2C4p42knhMHXOraljBfJIHmYkyBvGEbTOYdMPXh3sVeyQwaBYDDj7C
      RooXTgS1SwMKMvykc9sCQC9NrHG6hJbOnNqvOWOMcZ3iBW4Ni+cO6vxcHAWEcYIG
      FBnuZNqLWfWP3SGzuvB/TldIX2i++ilKirDSnXbt29o=
      -----END RSA PRIVATE KEY-----

    # openssl rsa -in jwt.pem -pubout
    publicKey: |
      -----BEGIN PUBLIC KEY-----
      MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCAzDxTx+zRtvJHX3a7MU1xBBBQ
      0/d1orZ7gPvzMGyo4S06/CRdu85rNqwkNLbYeYkQkUYuw0zeLFKFqI04WWg8Gavu
      y/gGBd4jAZEHjMZo4GCnXGEu8Bkib4fSukm8m+63zWCpwL7tHjLpqqFzsMY0tRTC
      JV/LxZIdvUDAZZk18QIDAQAB
      -----END PUBLIC KEY-----
