server:
  port: 9002
#  servlet:
#    context-path: /std
#当前配置环境
spring:
  profiles:
    active: dev
  application:
    name: pandaz-mongodb
  #允许多个bean调用同一个服务
  main:
    allow-bean-definition-overriding: true
