spring:
  cloud:
    #nacos
    nacos:
      discovery:
        server-addr: 10.211.55.3:8848

#mongodb配置
mongodb:
  primary:
    host: 10.135.12.156:37017
    name: test
    user:
    pwd:
  secondary:
    host: 10.135.12.156:37017
    name: test
    user:
    pwd:

#自定义属性
custom:
  #项目基础包
  projectPackage: com.pandaz
