spring:
  cloud:
    #nacos
    nacos:
      discovery:
        server-addr: 172.16.2.130:8848
    #sentinel
    sentinel:
      transport:
        dashboard: 172.16.2.130:8787

    stream:
      bindings:
        input:
          destination: queue.log.messages #要和output的destination一致, 这样才能将队列和写入消息的exchange关联起来
          group: logMessageConsumers
        output:
          destination: queue.log.messages
      binders:
        vm_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 172.16.2.130
                port: 5672
                username: pandaz
                password: pandaz
                virtual-host: my_vhost

#自定义属性
custom:
  #项目基础包
  projectPackage: com.pandaz
