spring:
  cloud:
    # nacos
    nacos:
      discovery:
        server-addr: localhost:8848
    # sentinel
    sentinel:
      transport:
        dashboard: localhost:8787
      log:
        dir: logs/task/sentinel

# 自定义属性
custom:
  # 项目基础包
  projectPackage: com.pandaz