spring:
  cloud:
    # nacos
    nacos:
      discovery:
        group: '@nacos.group@'
        server-addr: '@nacos.server.addr@'
    # sentinel
    sentinel:
      transport:
        dashboard: '@sentinel.dashboard.addr@'
      log:
        dir: logs/task/sentinel

# 自定义属性
custom:
  # 项目基础包
  projectPackage: com.github.pandaz